version: "3.9"
services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://user-service-mongo:27017/user-service
      - PORT=3000
    depends_on:
      - user-service-mongo

  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://appointment-service-mongo:27017/appointment-service
      - USER_SERVICE_URL=http://user-service:3000/api
      - PORT=3001
    depends_on:
      - appointment-service-mongo
      - user-service

  user-service-mongo:
    image: mongo:6.0
    container_name: user-service-mongo
    ports:
      - "27017:27017"
    networks:
      - microservices-network

  appointment-service-mongo:
    image: mongo:6.0
    container_name: appointment-service-mongo
    ports:
      - "27018:27017"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
